#!/usr/local/bin/perl
# return date mod for a file 
# THVV

#  Permission is hereby granted, free of charge, to any person obtaining
#  a copy of this software and associated documentation files (the
#  "Software"), to deal in the Software without restriction, including
#  without limitation the rights to use, copy, modify, merge, publish,
#  distribute, sublicense, and/or sell copies of the Software, and to
#  permit persons to whom the Software is furnished to do so, subject to
#  the following conditions:

#  The above copyright notice and this permission notice shall be included
#  in all copies or substantial portions of the Software.

#  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
#  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
#  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
#  IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
#  CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
#  TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
#  SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE. 

$values{'version'} = '1.0';
$values{'me'} = 'filemodshort';

$fn = $ARGV[0];
if (-f $fn) {
    ($dev,$ino,$mode,$nlink,$uid,$gid,$rdev,$size,
     $atime,$mtime,$ctime,$blksize,$blocks) = stat($fn);
    ($sec,$min,$hour,$mday,$mon,$year,$wday,$yday,$isdat) = localtime($mtime);

    $year -= 100 if $year >= 100;
    $year = &twodigit($year);
    $mday = &twodigit($mday);
    $mon = &twodigit($mon+1);
    
    print "$mon/$mday/$year\n";
} else {
    print "$fn not found\n";
}

# prettifier for dates
# $val = &twodigit ($field)
sub twodigit {			# returns field with leading zero if necessary
    local($x) = $_[0];
    return "$x" if ($x > 9);
    return "0$x";
} # twodigit
